version: "{build}"

skip_tags: true

environment:
  appveyor_repo_tag: true
  matrix:
    - FEATURE: HUGE

matrix:
  fast_finish: true

build_script:
  - src/appveyor.bat

#test_script:
#  - cd src/testdir
#    # Testing with MSVC gvim
#  - path C:\Python35-x64;%PATH%
#  - nmake -f Make_dos.mak VIMPROG=..\gvim
#  - nmake -f Make_dos.mak clean
#    # Testing with MingW console version
#  - nmake -f Make_dos.mak VIMPROG=..\vim

artifacts:
  - path: src\tabsidebar-vim-binaries.zip
    name: release

deploy:
  - provider: GitHub
    auth_token:
      secure: I/adDAeOOwlIfiqw2j1C7zhExhLcZige7Fe1ebFNvmJgv/1mvMl8VljAZlkQRJ81
    artifact: release
    draft: false
    prerelease: true

# vim: sw=2 sts=2 et ts=8 sr
